"""Initial revision

Revision ID: c3b05e91f67e
Revises: 551b2ab99846
Create Date: 2025-07-10 19:50:40.052312

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "c3b05e91f67e"
down_revision: Union[str, Sequence[str], None] = "551b2ab99846"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
